@extends('layout')


<style>
    /* CSS for Contact Section */

    .section {
        padding: 60px 0;
    }

    .section-sm {
        padding: 30px 0;
    }

    .container {
        width: 100%;
        max-width: 1140px;
        margin-left: auto;
        margin-right: auto;
        padding-left: 15px;
        padding-right: 15px;
    }

    .layout-bordered {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    .layout-bordered-item {
        flex-basis: 33.33%;
        /* Set the width to 33.33% to display three blocks inline */
        max-width: 33.33%;
        text-align: center;
        padding: 30px;
    }

    .icon {
        font-size: 40px;
        margin-bottom: 20px;
        color: black;
        /* Change the icon color to black */
    }

    .list-0 {
        padding-left: 0;
        list-style: none;
    }

    .list-0 li {
        margin-bottom: 10px;
        color: black;
        /* Change the text color to black */
    }

    .link-default {
        /* color: #007bff; */
        color: black;
    }

    .link-default:hover {
        text-decoration: none;
    }

    .icon-lg {
        font-size: 60px;
    }

    .mdi {
        background-color: transparent;
    }

    .text-primary {
        color: black;
        /* Change the text color to black */
    }

    .layout-bordered-item-inner {
        /* position: relative; */
        transition: 0.4s;
    }

    .wow-outer {
        position: relative;
    }

    .slideInUp {
        animation-name: slideInUp;
        animation-duration: 0.7s;
        visibility: visible !important;
    }

    @keyframes slideInUp {
        from {
            transform: translateY(50px);
            opacity: 0;
        }

        to {
            transform: translateY(0);
            opacity: 1;
        }
    }

    .icons {
        font-size: 40px;
        margin-bottom: 40px;
        color: #2f77ad;
    }
</style>


@section('body')
    <div class="page-banner overlay-black  mobile-responsive-header" style="padding: 150px 0 ; margin-top: -90px;">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <h1 class="page-banner-title color-primary">A Place You Call Home</h1>
                    <div class="text-area w-50 mt-15 color-white">
                        <p>About Us!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class=" featured-properties bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="main-title w-75 mx-auto d-table text-left mb-30">
                        <h2 class="title mb-20 color-secondary">Terms And Conditions</h2>
                        <span class="sub-title" style="font-size: 135%">
                            <ul>
                                <li><span style="font-size:14pt"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.5pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">By using&nbsp;&nbsp;</span></span><a href="http://www.syedzameen.com" style="color:blue; text-decoration:underline"><span style="font-size:12.5pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">www.syedzameen.com</span></span></a><span style="font-size:12.5pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;&nbsp;or the Syed Zameen mobile application of the online platform (collectively, the&nbsp;<strong>&quot;Website&quot;</strong>), you confirm that you have read, understood and accept these terms of use along with the privacy policy (the&nbsp;<strong>&quot;Terms&quot;</strong>) as the terms which govern your access to and use of the Website and the Service and you agree to comply with them. If you do not accept or agree to comply with these Terms, you must not use this Website. Additionally, when using a portion of the Service, you agree to conform to any applicable posted guidelines for such Service, which may change or be updated from time to time at our sole discretion.</span></span></span></span></span></li>
                                <li><span style="font-size:14pt"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.5pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">These Terms are made between Zameen Real World SMC (Private) Limited (<strong>&quot;we&quot;</strong>&nbsp;<strong>&quot;us&quot;</strong>&nbsp;<strong>&quot;our&quot;</strong>, the&nbsp;<strong>&quot;Company&quot;</strong>, as applicable) and you (<strong>&quot;you&quot;</strong>&nbsp;or the&nbsp;<strong>&quot;User&quot;</strong>). </span></span></span></span></span></li>
                                <li><span style="font-size:14pt"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.5pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">If you are a company advertising on our Website, you will be required to enter into additional terms and conditions set out in our Advertising Agreement, however, please note that these Terms will still apply and must be read in conjunction with any other agreement you enter into with the Company.</span></span></span></span></span></li>
                            </ul>
                            
                            <p style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;"><span style="color:#1f1f1f">DEFINITIONS</span></span></span></strong></span></span></span></p>
                            
                            <p style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;"><span style="color:#1f1f1f">The following capitalized terms shall have the following meaning, except where the context otherwise requires:</span></span></span></span></span></span></p>
                            
                            <ol>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Advertising Agreement&quot;</strong>&nbsp;&ndash; an agreement for the provision of advertising services or products entered into between the Company and the Client.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Ad Services Package&quot;</strong>&nbsp;&ndash; the bundle of advertising product or service which the Company agrees to provide to the Customer, as set out in the relevant order form provided by the Company and signed by the Client to order the Ad Services Package pursuant to these Terms and the terms of the Advertising Agreement.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Affiliates&quot;</strong>&nbsp;&ndash; any company that is controlled or owned by syedzameen, any company commonly controlled or owned by syedzameen and any Syed Real Estate Group entity jointly offering the Service.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Syed Zameen&quot;</strong>&nbsp;&ndash; Zameen Real World SMC (Private) Limited which is the owner of&nbsp;</span></span><a href="http://www.syedzameen.com" style="color:blue; text-decoration:underline"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">www.syedzameen.com</span></span></a><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;and whose registered office is Plaza No 28, , Block-F, 1<sup>st</sup> Floor Commercial Area DHA Phase-1, Lahore.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Client&quot;</strong>&nbsp;- the client entity that is party to the Advertising Agreement.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Customer&quot;</strong>&nbsp;- any customer of the Client.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Effective Date&quot;</strong>&nbsp;- the date set out at the top of these Terms.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Intellectual Property Rights&quot;</strong>&nbsp;- all intellectual property, including patents, trade marks, rights in goodwill, database rights and rights in data, rights in designs, copyrights and topography rights (whether or not any of these rights are registered, and including applications and the right to apply for registration of any such rights) and all inventions, rights in know-how, trade secrets and confidential information, customer and supplier lists and other proprietary knowledge and information and all rights under licences and consents in relation to any such rights and all rights and forms of protection of a similar nature or having equivalent or similar effect to any of these which may subsist anywhere in the world for their full term, including any renewals and extensions.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Material&quot;</strong>&nbsp;- material and content published on the Website or otherwise provided by the Company in connection with the Service.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Privacy Policy</strong>&nbsp;- the privacy policy of the Company from time to time</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Product&quot;</strong>&nbsp;- an online classifieds advertising platform provided on the Website and the Ad Services Package.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Posting Agents&quot;</strong>&nbsp;- a third-party agent, service or intermediary that offers to post Material to the Service on behalf of others.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Registration Details&quot;</strong>&nbsp;- the details a User must provide upon registering for the Website from time to time (for example: name, phone numbers, email address, age and/or address).</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Service&quot;</strong>&nbsp;- the provision of the Website and the Product.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;<strong>&quot;Unacceptable&quot;</strong>&nbsp;- any material or information uploaded to or made available on the Website which under the law of any jurisdiction from which the Website may be accessed may be considered:</span></span></span></span></span></span>
                                <ol>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">illegal, illicit, indecent, obscene, racist, offensive, pornographic, pedophilic, insulting, false, unreliable, misleading, harmful or potentially harmful to minors, threatening, libelous, alleged to be or actually defamatory or in infringement of third-party rights (of whatever nature and including, without limitation, any Intellectual Property Rights), invasive of another&rsquo;s privacy or other rights, to relate to or encourage money laundering or illegal gambling;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">in breach of any applicable laws, regulations, standards or codes of practice (notwithstanding that compliance may not be compulsory);</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">in contravention of legislation, including without limitation, that relating to weapons, animals or alcohol; or</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">harmful to the Company&rsquo;s reputation.</span></span></span></span></span></span></li>
                                </ol>
                                </li>
                            </ol>
                            
                            <p style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;"><span style="color:#1f1f1f">GENERAL TERMS AND CONDITIONS WHICH APPLY TO USERS</span></span></span></strong></span></span></span></p>
                            
                            <ol>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">In registering for this Website, the User must provide true, accurate, current and complete Registration Details which the User must update after any changes (except age) before using the Website for further services in the future.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The User hereby agrees and acknowledges that the Website may contain adverts placed by advertisers or companies in the course of business for goods or services (and which the Company takes no responsibility for). Advertisers or companies using the Website or the Service to place adverts offering goods or services of a business, commercial or trade nature must include their full names in the advert and make it clear that they are selling goods or services in the course of business either by the content, format, size or place of the advertisement or by including words such as &ldquo;trade&rdquo;, &ldquo;dealer&rdquo;, &ldquo;agent&rdquo;, &ldquo;wholesale&rdquo; or similar in the name of the advert they submit for publication.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The User hereby warrants and represents to the Company that it is at least Four, years of age and has the lawful authority to enter into contracts and publish User Material on the Website.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Company reserves the discretion to withdraw any Material or User Material from the Website without prior notice and to refuse any User Material posted or provided to the Company by a User.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The User&rsquo;s Registration Details and data relating to its use of the Website will be recorded by the Company but this information shall not be disclosed to third parties (otherwise than on an aggregated, anonymous basis, or in accordance with the Privacy Policy or in accordance with Clause 2.6 below) nor used for any purpose unrelated to the Website. By agreeing to the terms, you expressly give us permission to verify the authenticity of your details by calling you on the phone number submitted to us. The call may be recorded for quality assurance.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The User hereby authorizes the Company to use any information which it submits to the Website to inform the User of special offers, occasional third party offers and for other marketing and related purposes. Without prejudice to Clause 2.5 above, the Company will not use User data for any other purposes than as set out in these Terms except that the Company may disclose this data if compelled to do so by law, or at the request of a law enforcement agency or governmental authority.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">If the User does not wish the Company to use its information as set out in Clause 2.6 above, it should leave the Website before submitting its personal details.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">If the User does not want the Company to use its email address or SMS/mobile number to send information concerning the Website and related matters, the User should send an email message the syedzameensite@gmail.com&nbsp;and insert unsubscribe as the subject heading of such message.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">You must keep confidential any user identification and password details set-up or given to you as part of our security procedures and must not disclose them to any third party.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Company reserves the right to suspend or terminate a user&rsquo;s account where, in its absolute discretion, it deems the User has breached these terms or deems such suspension or termination is otherwise appropriate. In the event of such suspension or termination, the Company will notify the User by email and the User must not seek to re-register on any Website either directly or indirectly through a related entity. The Company&rsquo;s rights under this Clause 2.10 shall not prejudice any other right or remedy the Company may have in respect of any breach, or any rights, obligations or liabilities accrued prior to such suspension or termination.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">For the avoidance of doubt, the Company is providing a service not goods.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Syed Zameen owns all Intellectual Property Rights in and associated with the Website and the Service, including without limitation, any trademarks, trade names, designs, text, graphics and the selection and arrangement thereof. Nothing contained in the Website should be construed as granting by implication or otherwise, any license or right to use any trademark displayed on the Website without our written permission. You may print off one copy, and may download extracts, of any page(s) from the Website for your personal use and you may draw the attention of others to content posted on the Website but you must not modify the digital or paper copies of any materials you have printed off or downloaded in any way, and you must not use any photographs or videos separately from any accompanying text. You agree not to circumvent, disable or otherwise interfere with security related features of the Website or features that prevent or restrict use or copying of any Materials or enforce limitations on use of the Website or the Materials therein. Material displayed on or through the Service is protected by copyright as a collective work and/or compilation, pursuant to copyrights laws, other laws, and international conventions. Any reproduction, modification, creation of derivative works from or redistribution of the Website, the Materials, or the collective work or compilation is expressly prohibited. Copying or reproducing the Website, the Materials, or any portion thereof for further reproduction or redistribution is expressly prohibited.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Company takes reported and actual infringement of Intellectual Property Rights and fraud extremely seriously and whilst Users cannot hold the Company liable in relation to such issues, the Company requests all Users to report such matters immediately to the Company, and the Company inform the appropriate authorities.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;If you are an owner of Intellectual Property Rights or an agent who is fully authorized to act on behalf of the owner of Intellectual Property Rights and believe that any Material or other content infringes upon your Intellectual Property Right or the Intellectual Property Rights of the owner on whose behalf you are authorized to act, you may submit a notification to the Company together with a request to the Company to delete the relevant Material in good faith. The notification and the request must contain the following information:</span></span></span></span></span></span>
                                <ol>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">identification of the Intellectual Property Rights claimed to have been infringed, or, if multiple Intellectual Property Rights can be covered by a single notification, a representative list of such works;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">identification of the Material (by means of data or communication link, etc.) that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the Company to locate the Material;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">information reasonably sufficient to permit the Company to contact you, such as an address, telephone number, and an electronic mail address;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">a signed statement that you have a good faith belief that use of the Material in the manner complained of is not authorised by the Intellectual Property Rights owner, its agent, or the law;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">a signed statement that the Intellectual Property Rights owner holds the Company harmless from any claim of any third party in connection with the Company removing the relevant content; and</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">a signed statement that the information in the notification is accurate and under penalty of perjury that you are authorised to act on behalf of the owner of an exclusive right that is allegedly infringed.</span></span></span></span></span></span></li>
                                </ol>
                                </li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">All notifications under Clauses 2.13 and 2.14 must be sent to&nbsp;syedzameensite@gmail.com</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">Users will be invited to send comments to the Company email relating to the integrity and performance of other Users.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">&nbsp;The following restrictions shall apply to all Users. You must:</span></span></span></span></span></span>
                                <ol>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not use the Website or the Service in any unlawful manner, for any unlawful purpose, or in any manner inconsistent with these Terms, or act fraudulently or maliciously, for example, by hacking into or inserting malicious code, such as viruses, or harmful data, into the Website or any Service or any operating system;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not transmit any material designed to interrupt, damage, destroy or limit the functionality of the Website or the Service;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">use any form of automated device or computer program (sometimes referred to as &ldquo;flagging tools&rdquo;) that enables the use of the Company&rsquo;s &ldquo;flagging system&rdquo; or other community control systems without each flag being manually entered by a human that initiates the flag (an &ldquo;automated flagging device&rdquo;), or use any such flagging tool to remove posts of competitors, other third parties or to remove posts without a reasonable good faith belief that the post being flagged violates these terms or any applicable law or regulation;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not use any automated software to view the Service without our consent (including use of spiders, robots, crawlers, data mining tools, or the like to download or scrape data from the Service, except for internet search engines (e.g, Google) and non-commercial public archives (e.g. archive.org) that comply with our robots.txt file) and only access the Service manually;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not use the Service other than for your own personal use or as an agent listing property for sale and to rent;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not attempt to copy any Material or reverse engineer any processes without the Company&rsquo;s consent;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not use any Service in any manner that is illegal, immoral or harmful to the Zameen Real World SMC (Private) Limited and/or Syed Real Estate And Builders;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not use any Service in breach of any policy or other notice on the Website;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not remove or alter any copyright notices that appear on the Website;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not publish any User Material which is or may be Unacceptable or that may encourage a breach of any relevant laws or regulations;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not interfere with any other User&rsquo;s enjoyment of the Website or the Service;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not conduct yourself in an offensive or abusive manner whilst using the Website or the Service;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not contact anyone who has asked not to be contacted, or make unsolicited contact with anyone for any commercial purpose, specifically, contact any User to post advertisement on a third party website or post any advertisement on behalf of such User;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not &quot;stalk&quot; or otherwise harass anyone;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not collect personal data about other Users or entities for commercial or unlawful purposes;</span></span></span></span></span></span></li>
                                    <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">not transmit any User Material that:</span></span></span></span></span></span>
                                    <ol>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">harasses, degrades, intimidates or is hateful towards any individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age or disability;</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">includes personal or identifying information about another person without that persons&#39;s explicit consent;</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">impersonates any person or entity, including, but not limited to, a Company employee, or falsely states or otherwise misrepresents an affiliation with a person or entity;</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">is protected by copyright or patent, protected by trade secret or trademark, or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission or a license from their rightful owner to post the material and to grant the Company all of the license rights granted herein;</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">infringes any of the foregoing Intellectual Property Rights of any party, or is User Material that you do not have a right to make available under any law, regulation, contractual or fiduciary relationship(s);</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">constitutes or contains &quot;pyramid schemes&quot;, &quot;jokes&quot;, &quot;affiliate marketing,&quot; &quot;link referral code,&quot; &quot;junk mail,&quot; &quot;spam,&quot; &quot;chain letters,&quot; &quot;bait marketing&quot;, &quot;negative option marketing&quot;, &quot;referral selling&quot; or unsolicited advertisements of a commercial nature;</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">constitutes or contains any form of advertising or solicitation if: (i) posted in areas or categories of the Website which are not designated for such purposes; or (ii) e-mailed to the Company Users who have requested not to be contacted about other services, products or commercial interests; and</span></span></span></span></span></span></li>
                                        <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">includes links to commercial services or third party websites, except as specifically allowed by the Company.</span></span></span></span></span></span></li>
                                    </ol>
                                    </li>
                                </ol>
                                </li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">By submitting User Material on the Website or otherwise, the User grants Syed Zameen a royalty-free, perpetual, irrevocable and non-exclusive right and license to use, reproduce, distribute, display, modify and edit the User Material. Syed Zameen will not pay the User any fees whatsoever for the User Material and reserves the right in its sole discretion to remove or edit the User Material at any time. The User warrants and represents that it has all rights, consents and/or authorizations in respect of the User Material necessary to grant Syed Zameen these rights.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Company permits the User to post User Material on the Website in accordance with the Company&rsquo;s procedures provided that User Material is not illegal, misleading, obscene, abusive, threatening, defamatory or otherwise objectionable to the Company. You must not post any Unacceptable material and, in respect of any User Material you post, you warrant that it is not Unacceptable.</span></span></span></span></span></span></li>
                                <li style="text-align:justify"><span style="font-size:14pt"><span style="background-color:white"><span style="color:#1f1f1f"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:12.0pt"><span style="font-family:&quot;Lato&quot;,&quot;sans-serif&quot;">The Company grants you a limited, revocable, non-exclusive license to access and use the Service for personal use. This license granted herein does not include any of the following: (a) access to or use of the Service by Posting Agents; or (b) any collection, aggregation, copying, duplication, display or derivative use of the Service nor any use of data mining, robots, spiders, or similar data gathering and extraction tools for any purpose unless expressly permitted by the Company or as otherwise set forth in these Terms. Notwithstanding the foregoing, general purpose internet search engines and non-commercial public archives that gather information for the sole purpose of displaying hyperlinks to the Service, provided they each do so from a stable IP address or range of IP addresses using an easily identifiable agent and comply with our robots.txt file, may engage in the activities set forth in (b). For purposes of this exception, a &ldquo;general purpose internet search engine&rdquo; does not include a website or search engine or other service that specializes in classified listings including any subset of classifieds listings such as housing, for sale, jobs, services, or personals, or which otherwise provides classified ad listing services. The license set forth in this Clause 2.20 permits you to display on your website, or create a hyperlink thereto, individual postings on the Service so long as such use is for non-commercial and/or news reporting purposes only (e.g., for use in personal blogs or other personal online media). The Company may limit the number of postings displayed on or linked to your website. Use of the Service beyond the scope of authorized access as set forth in these Terms immediately terminates any permission or license granted herein. In order to collect, aggregate, copy, duplicate, display or make derivative use of the Service or any Material made available via the Service for other purposes (including commercial purposes) not stated herein, you must first obtain a license from the Company.</span></span></span></span></span></span></li>
                            </ol>
                            
                            <p>&nbsp;</p>
                            
                        </span>
                    </div>
                </div>


            </div>
        </div>

    </section>
@endsection
